
disableKinds = ["RSS", "sitemap", "robotsTXT"]
baseURL = '/'
languageCode = ''
title = 'Jael Hernandez'

[taxonomies]
tag = ""
category = ""

[[params.social]]
name = "photos"
url = "https://instagram.com/jaez.jpg"

[[params.social]]
name = "videos"
url = "https://youtube.com/@alejandrojaelhernandez"

[[params.social]]
name = "articles"
url = "https://alejandrojaez.substack.com/"

[[params.social]]
name = "videogames"
url = "https://games.jaelhernandez.com"

[[params.social]]
name = "programming"
url = "https://jaezdev.pages.dev"
